# Lighthouse-Keeper | GitHub Action
# 
# Description: Generates & adds manually/automatically Lighthouse badges & reports from one/multiple input URL(S) to a selected target repository
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-keeper-action
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Keeper'
author: 'Sitdisch'
description: "Generates & adds manually/automatically Lighthouse badges & reports from one/multiple input URL(S) to a selected repository"
branding:
  icon: search
  color: yellow

inputs:
  path:
    description: 'Path to place the results'
    required: true
  user-name:
    description: 'User who should commit'
    required: true
  user-email:
    description: 'User e-mail address'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Mobile Results
      run: |
        mkdir ${{ inputs.path }}
        cd temp_lighthouse_badges_nested
        export LIGHTHOUSE_BADGES_PARAMS="--throttling.cpuSlowdownMultiplier=2"
        ./src/index.js -u https://mythemeway.github.io -b pagespeed -o mobile
        cp -r mobile ../${{ inputs.path }}
        cd ..
      shell: bash
    - name: Commit Results
      run: |
        git config --local user.email ${{ inputs.user-email }}
        git config --local user.name ${{ inputs.user-name }}
        git add ${{ inputs.path }}
        git commit -am "| Lighthouse Results Added"
        git push
      shell: bash
