# Lighthouse-Badger | GitHub Action
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL-group(s) to one/multiple target repo(s)/branch(es)
# Author: Sitdisch
# Version: v1.1
# Source: https://github.com/myactionway/lighthouse-badger-action
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Badger'
author: 'Sitdisch'
description: "Generates, adds & updates manually/automatically Lighthouse badges & reports from 1,2... URL(s) to 1,2... repo(s)/branch(es)"
branding:
  icon: bold
  color: purple

inputs:
  urls:
    description: 'URL(s) to be checked'
    required: true
  badges-args:
    description: 'Badges arguments: -b, -l, -o, -r, -s'
    required: true
  results-type:
    description: 'Results type: mobile, desktop, both or both_p'
    required: true
  mobile-lighthouse-params:
    description: 'Lighthouse parameters mobile audit'
    required: true
  desktop-lighthouse-params:
    description: 'Lighthouse parameters desktop audit'
    required: true
  user-name:
    description: 'User who should commit'
    required: true
  user-email:
    description: 'User e-mail address'
    required: true
  commit-message:
    description: 'Commit message'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        RESULTS_PATH=`expr "${{ inputs.badges-args }}" : ".* --\?ou\?t\?p\?u\?t\?-\?p\?a\?t\?h\? \([^ ]*\).*"`;
        BADGES_ARGS=$(sed -e "s/ \(\(--output-path\)\|\(-o\)\) \S*//g" <<< "${{ inputs.badges-args }}" );
        RESULTS_TYPE=${{ inputs.results-type }}
        mkdir -p $RESULTS_PATH
        cd temp_lighthouse_badges_nested
        lighthouse_badger() {
          declare -A var
          var[LIGHTHOUSE_PARAMS]="$1-lighthouse-params"
          export LIGHTHOUSE_BADGES_PARAMS="${{ inputs[var[LIGHTHOUSE_PARAMS]] }}"
          echo ${{ var[LIGHTHOUSE_PARAMS] }}
          ./src/index.js -u ${{ inputs.urls }} $BADGES_ARGS -o $RESULTS_PATH/$1
          cp -r $RESULTS_PATH/$1 ../$RESULTS_PATH
        }
        if [[ ${RESULTS_TYPE:0:4} = "both" ]]; then
          if [[ ${RESULTS_TYPE:4} = "_p" ]]; then
            lighthouse_badger "mobile" &
            lighthouse_badger "desktop" &
            wait
          else
            lighthouse_badger "mobile"
            lighthouse_badger "desktop"
          fi
        else
          lighthouse_badger "$RESULTS_TYPE"
        fi
        cd ..
        git config --local user.email ${{ inputs.user-email }}
        git config --local user.name ${{ inputs.user-name }}
        git pull
        git fetch
        git add $RESULTS_PATH
        git commit -am "${{ inputs.commit-message }}"
        git push
      shell: bash
