# Lighthouse-Keeper | GitHub Action
# 
# Description: Generates & adds manually/automatically Lighthouse badges & reports from one/multiple input URL(S) to a selected target repository
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-keeper-action
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Keeper'
author: 'Sitdisch'
description: "Generates & adds manually/automatically Lighthouse badges & reports from one/multiple input URL(S) to a selected repository"
branding:
  icon: search
  color: yellow

inputs:
  urls:
    description: 'URL(s) to be checked'
    required: true
  results-path:
    description: 'Path to place the results'
    required: true
  badges-args:
    description: 'Badges arguments: -b {flat...}, -r, -s'
    required: true
  results-type:
    description: 'Results type: mobile, desktop, both'
    required: true
  mobile-lighthouse-params:
    description: 'Lighthouse parameters mobile'
    required: true
  desktop-lighthouse-params:
    description: 'Lighthouse parameters desktop'
    required: true
  user-name:
    description: 'User who should commit'
    required: true
  user-email:
    description: 'User e-mail address'
    required: true

runs:
  using: "composite"
  steps:
    - name: Make Directory
      run: mkdir -p ${{ inputs.results-path }}
      shell: bash
    - name: Create Mobile Results
      run: |
        if [ ${{ inputs.results-type }} = "both" ] || [ ${{ inputs.results-type }} = "mobile" ]; then
          cd temp_lighthouse_badges_nested
          export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.mobile-lighthouse-params }}"
          ./src/index.js -u ${{ inputs.urls }} ${{ inputs.badges-args }} -o mobile
          cp -r mobile ../${{ inputs.results-path }}
          cd ..
        fi
      shell: bash
    - name: Create Desktop Results
      run: |
        if [ ${{ inputs.results-type }} = "both" ] || [ ${{ inputs.results-type }} = "desktop" ]; then
          cd temp_lighthouse_badges_nested
          export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.desktop-lighthouse-params }}"
          ./src/index.js -u ${{ inputs.urls }} ${{ inputs.badges-args }} -o desktop
          cp -r desktop ../${{ inputs.results-path }}
          cd ..
        fi
      shell: bash
    - name: Commit Results
      run: |
        git config --local user.email ${{ inputs.user-email }}
        git config --local user.name ${{ inputs.user-name }}
        git add ${{ inputs.results-path }}
        git commit -am "Lighthouse-Keeper[bot]: Results Added"
        git push
      shell: bash
