# Lighthouse-Keeper | GitHub Action
# 
# Description: Generates & adds manually/automatically Lighthouse badges & reports from one/multiple input URL(S) to a selected target repository
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-keeper-action
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Keeper'
author: 'Sitdisch'
description: "Generates & adds manually/automatically Lighthouse badges & reports from one/multiple input URL(S) to a selected repository"
branding:
  icon: search
  color: yellow

inputs:
  urls:
    description: 'URL(s) to be checked'
    required: true
  path:
    description: 'Path to place the results'
    required: true
  badge-style:
    description: 'Badge Style: flat,plastic,social...'
    required: true
  single-badge:
    description: 'Output only a single-badge'
    required: true
  mobile-lighthouse-params:
    description: 'Additional Parameters for mobile assessment'
    required: true
  desktop-lighthouse-params:
    description: 'Additional Parameters for desktop assessment'
    required: true
  user-name:
    description: 'User who should commit'
    required: true
  user-email:
    description: 'User e-mail address'
    required: true

runs:
  using: "composite"
  steps:
    - name: Make Directory
      run: mkdir -p ${{ inputs.path }}
      shell: bash
    - name: Set Optional Arguments
      run: |
        if [ ${{ inputs.single.badge }} ]; then
          SINGLE-BADGE="-s"
        else
          SINGLE-BADGE=""
        fi
      shell: bash
    - name: Create Mobile Results
      run: |
        cd temp_lighthouse_badges_nested
        export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.mobile-lighthouse-params }}"
        ./src/index.js -u ${{ inputs.urls }} -b ${{ inputs.badge-style }} $SINGLE-BADGE -o mobile -r
        cp -r mobile ../${{ inputs.path }}
        cd ..
      shell: bash
    - name: Create Desktop Results
      run: |
        cd temp_lighthouse_badges_nested
        export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.desktop-lighthouse-params }}"
        ./src/index.js -u ${{ inputs.urls }} -b ${{ inputs.badge-style }} $SINGLE-BADGE -o desktop -r
        cp -r desktop ../${{ inputs.path }}
        cd ..
      shell: bash
    - name: Commit Results
      run: |
        git config --local user.email ${{ inputs.user-email }}
        git config --local user.name ${{ inputs.user-name }}
        git add ${{ inputs.path }}
        git commit -am "| Lighthouse Results Added"
        git push
      shell: bash
