name: 'Testaction'
author: 'Sitdisch'
description: 'Test your action'
inputs:
  new-first-commit:
    description: 'New first commit'
    required: true
  branch:
    description: 'Branch to be pruned'
    required: true
    default: 'master'
  user-name:
    description: 'User who should commit'
    required: true
    default: 'github-actions[bot]'
  user-email:
    description: 'User e-mail address'
    required: true
    default: '41898282+github-actions[bot]@users.noreply.github.com'
runs:
  using: "composite"
  steps:
    - run: |
        git config --local user.email ${{ inputs.user-email }}
        git config --local user.name ${{ inputs.user-name }}
        COMMIT_ID=$(git rev-parse ${{ inputs.new-first-commit }})
        COMMIT_MESSAGE=$(git log --format=%B -n 1 "$COMMIT_ID" )" [ Test[bot]: Earlier Commits Truncated ]"
        
        git checkout --orphan test_temp "$COMMIT_ID"
        git commit -m "$COMMIT_MESSAGE"
        git rebase --onto test_temp $COMMIT_ID ${{ inputs.branch }}
        git branch -D test_temp
        git push origin HEAD --force
      shell: bash
